# Generated by Django 3.1.7 on 2021-03-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210317_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discripation',
            field=models.TextField(default='anything'),
        ),
    ]
