# Generated by Django 3.1.7 on 2021-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_discripation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'TOP Wear'), ('BW', 'Bottom Wear'), ('ID', 'Indian Dress'), ('D', 'Dress'), ('H', 'HeadPhone')], max_length=2),
        ),
    ]
