# Generated by Django 3.1.7 on 2021-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210325_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'TOP Wear'), ('BW', 'Bottom Wear'), ('ID', 'Indian Dress'), ('D', 'Dress'), ('F', 'Fitness&Sport')], max_length=2),
        ),
    ]
