# Generated by Django 3.1.7 on 2021-03-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210328_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'TOP Wear'), ('BW', 'Bottom Wear'), ('ID', 'Indian '), ('D', 'Dress'), ('S', 'gym supplements'), ('E', 'gym equipment')], max_length=2),
        ),
    ]
